name: Create Packages
on:
  release:
    types: [published]

jobs:
  CPack-Package-Build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - release: ubuntu-2004
            extension: ".deb"
            OS-name: "ubuntu/focal"
          - release: ubuntu-2010
            extension: ".deb"
            OS-name: "ubuntu/groovy"
          - release: ubuntu-2104
            extension: ".deb"
            OS-name: "ubuntu/hirsute"
          - release: centos8
            extension: ".rpm"
            OS-name: "el/8"
          - release: fedora-34
            extension: ".rpm"
            OS-name: "fedora/34"
          # build issue on fedora 35
          # - release: fedora-35
          #   extension: ".rpm"
          #   OS-name: "fedora/35"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Packagecloud CLI
        run: sudo apt-get -y install ruby-full && sudo gem install package_cloud

      - name: Build Container
        run: docker build . -f ./.github/images/${{ matrix.release }}/Dockerfile  -t package_builder

      - name: Packaging
        run: docker run -e DOMAIN_SIZE="64bit" --name container -t package_builder 

      - name: Extract
        run: docker cp container:/souffle/build/ .

      - name: Upload
        run: cd build && PACKAGECLOUD_TOKEN=${{ secrets.PACKAGECLOUD_TOKEN }} package_cloud push souffle-lang/souffle/${{ matrix.OS-name }} "$(ls *${{ matrix.extension }} | head -n1)"
